# -*- coding: utf-8 -*-
"""Intrusion_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZmhqMwkv8dcfHWEvmniVR3hmA8x9pT6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the dataset
file_name = "train_test_networkP.csv"
df = pd.read_csv(file_name)

# Display dataset shape and columns
print("Dataset Shape:", df.shape)
print("Columns:", df.columns)

import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Split Labeled (5%) and Unlabeled (95%)
labeled_df = df.sample(frac=0.05, random_state=42)
unlabeled_df = df.drop(labeled_df.index)

# Display the split
print("Labeled Data Shape:", labeled_df.shape)
print("Unlabeled Data Shape:", unlabeled_df.shape)

from sklearn.model_selection import train_test_split

label_column = "Label"  # Change if your label column has a different name

# Drop labels from the Unlabeled Dataset
unlabeled_df_no_label = unlabeled_df.drop(columns=[label_column])

# Further split Unlabeled Data (Train 90% / Test 10%)
unlabeled_train_df, unlabeled_test_df = train_test_split(unlabeled_df_no_label, test_size=0.10, random_state=42)

# Display updated split sizes
print("Unlabeled Training Data Shape (without labels):", unlabeled_train_df.shape)
print("Unlabeled Testing Data Shape (without labels):", unlabeled_test_df.shape)

